ServiceName = "theservicename"
Name = "theservicename"
Description = "wtf"
Owners = ["nadaverell@gmail.com"]
ServerFramework = "go-server"
ServerMain = ""
ArtifactRepository = "me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo"
Domain = "cluster.koalaops.com"
Port = 8080

[Repo]
  Name = "theservicename"
  GitUser = "koala-sandbox"
  URL = "https://github.com/koala-sandbox/theservicename"
  Token = ""

[OpenAPIConfig]
  SpecPath = ""
  CodegenTool = ""

[[Environments]]
  Name = "dev"
  Namespace = "dev"
  Cluster = "koala-demo-cluster"
  IngressEnabled = true
  IngressHost = ""
  [Environments.EnvDeploymentConfig]
    AutoDeploy = true

[[Environments]]
  Name = "prod"
  Namespace = "prod"
  Cluster = "koala-demo-cluster"
  IngressEnabled = true
  IngressHost = ""
  [Environments.EnvDeploymentConfig]
    AutoDeploy = false

[SSLConfig]
  CertName = "theservicename-tls-cert"
  Issuer = "letsencrypt"
  IssuerContactEmail = "nadav@koalaops.com"

[Tracing]
  Backend = ""
  URL = ""

[Profiling]
  Tool = ""
